-- Create Project Table
create table public.project (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null,
  description text,
  image_path text,
  is_deleted boolean default false,
  user_id uuid references auth.users not null default auth.uid()
);

-- Create Expense Table
create table public.expense (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references public.project(id) on delete cascade not null,
  amount double precision not null,
  amount_bgn double precision,
  description text not null,
  category text,
  date timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS (Row Level Security)
alter table public.project enable row level security;
alter table public.expense enable row level security;

-- Create Policy: Users can only see/edit their own projects
create policy "Users can operate on their own projects"
on public.project
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Create Policy: Users can only see/edit expenses of their own projects
create policy "Users can operate on expenses of their own projects"
on public.expense
for all
to authenticated
using (
  exists (
    select 1 from public.project
    where public.project.id = public.expense.project_id
    and public.project.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.project
    where public.project.id = public.expense.project_id
    and public.project.user_id = auth.uid()
  )
);

-- STORAGE SETUP
-- Create the bucket
insert into storage.buckets (id, name, public) 
values ('gk-deals-expenses-images', 'gk-deals-expenses-images', true);

-- Policy: Allow public access to view images
create policy "Project Images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'gk-deals-expenses-images' );

-- Policy: Allow authenticated users to upload images
create policy "Authenticated users can upload project images"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'gk-deals-expenses-images' );

-- Policy: Allow authenticated users to update their images
create policy "Authenticated users can update their images"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'gk-deals-expenses-images' );

-- Policy: Allow authenticated users to delete their images
create policy "Authenticated users can delete their images"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'gk-deals-expenses-images' );
